import "./globals.css";
import type { Metadata } from "next";
import { Josefin_Sans as Josefin } from "next/font/google";
import Providers from "./hooks/Providers";
import ThemeButton from "./components/header/ThemeButton";
import Header from "./components/header/Header";

const josefin = Josefin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${josefin.className} mx-auto w-[85%] max-w-[34rem] bg-veryLightGray dark:bg-veryDarkBlue`}
      >
        <Providers>
          <Header />
          <div className="absolute left-0 right-0 top-0 -z-50 h-[30rem]  w-full bg-[url(/bg-mobile-light.jpg)] bg-contain bg-no-repeat dark:bg-[url(/bg-mobile-dark.jpg)] sm:bg-[url(/bg-desktop-light.jpg)] dark:sm:bg-[url(/bg-desktop-dark.jpg)]"></div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
